name: UI Tests

on: push

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest
      - name: Install rsync 📚
        run: |
          sudo apt-get install rsync
      - name: Move Pyreport to Public Directory
        run: |
          mkdir public
          mv pyreport.html public/
      - name: Checkout (copy) gh-pages repository to GitHub runner
        uses: actions/checkout@v2
        if: always()
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: always()
        with:
          token: ${{ secrets.TOKEN_CI }}
          branch: gh-pages
          folder: public
          #clean: true